CI: skip changed-files action on tag
The changed-files action fails when pushing a tag:

  Error: Similar commit hashes detected: previous sha: a9cf47f4429ec2552ccb3c8d4241dcda29ea7bef is equivalent to the current sha: a9cf47f4429ec2552ccb3c8d4241dcda29ea7bef.
  Error: Please verify that both commits are valid, and increase the fetch_depth to a number higher than 50.
  Error: Similar commit hashes detected.

(cherry picked from commit 440ca8833d48484b3cd07f14380efa8f1c462150)