tasks: fix WILLOW_DEBUG_RUNTIME_STATS
The FreeRTOS task functions require inclusion of freertos/task.h.

Fixes the following compile error:

/willow/main/tasks.c: In function 'task_debug_runtime_stats':
/willow/main/tasks.c:9:9: error: implicit declaration of function 'vTaskGetRunTimeStats'; did you mean 'xTaskGetIdleRunTimeCounter'? [-Werror=implicit-function-declaration]
         vTaskGetRunTimeStats(buf);
         ^~~~~~~~~~~~~~~~~~~~
         xTaskGetIdleRunTimeCounter
/willow/main/tasks.c:11:9: error: implicit declaration of function 'vTaskDelay' [-Werror=implicit-function-declaration]
         vTaskDelay(5000 / portTICK_PERIOD_MS);
         ^~~~~~~~~~
/willow/main/tasks.c:13:5: error: implicit declaration of function 'vTaskDelete' [-Werror=implicit-function-declaration]
     vTaskDelete(NULL);
     ^~~~~~~~~~~