audio: check if CONFIG_TASK_WDT_PANIC is defined
And define it to the same value used in sdkconfig.willow if it doesn't.
Fixes the following error running clang-check:

/willow/main/audio.c:655:42: error: use of undeclared identifier 'CONFIG_TASK_WDT_PANIC' [clang-diagnostic-error]