Kconfig: fix WILLOW_DEBUG_TASKS
FreeRTOS` vTaskList function requires FREERTOS_USE_TRACE_FACILITY *and*
FREERTOS_USE_STATS_FORMATTING_FUNCTIONS to be enabled.

Fixes the following compile error:

/opt/esp/tools/xtensa-esp32s3-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32s3-elf/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld: esp-idf/main/libmain.a(main.c.obj):(.literal.app_main+0xfc): undefined reference to `vTaskList'
/opt/esp/tools/xtensa-esp32s3-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32s3-elf/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld: esp-idf/main/libmain.a(main.c.obj): in function `app_main':
/willow/main/main.c:718: undefined reference to `vTaskList'
collect2: error: ld returned 1 exit status

Closes #187.