utils.sh: nuke esptool install
The ESP-IDF container comes with esptool, and our local install seems to
cause issues with ESP-IDF 5.3 during dist build:

esptool.py v4.5.1
Wrote 0x1000000 bytes to file /willow/build/willow-dist-ESP32-S3-BOX.bin, ready to flash to offset 0x0
Combined firmware image for flashing written
-rw-r--r-- 1 root root 16M Apr 25 07:14 /willow/build/willow-dist-ESP32-S3-BOX.bin
/willow/venv/bin/python: No module named esp_idf_nvs_partition_gen
Error: Process completed with exit code 1.